### ISSUE TITLE
Improve the title background on the slider homepage 

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/morfeu-theme#1]
With light backgrounds, the title sometimes is hard to read. Maybe something more dark behind it can improve the view.

**Comment by fiquinho** [comment]
Hi, I will try to add something to improve the view. I'll get back to you as soon as I can!
See you!

**Comment by rodrigo-brito** [comment]
Thank you @fiquinho. Have fun! ❤️

**Comment by Minimilk93** [comment]
Would a simple overlay not be a solution?

**Comment by rodrigo-brito** [comment]
Be free to choose the solution, but something that looks good with the design.

**Comment by davidbru** [comment]
I proposed a fix with quadruple text-shadow..

A side note: You used sass and all, but you didn't include a package.json or something similar. So it was quite a challenge to emulate the same settings which you had.
I ended up using grunt-contrib-sass and then manually inserting the necessary lines into your style.css.
Otherwise I would have destroyed all your indentations in the compiled style.css.
